swagger: "2.0"
info:
  description: Phase 2 - Transactions
  version: 1.0.0
  title: "ArgentBank : API documentation for transactions"
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - https
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions for current month
      summary: An identified user can see all his transactions for the current month.
      description: >-
        API for fetching the transactions in the current month for an identified
        user
      operationId: readAllTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      responses:
        "200":
          description: Successfully get user's all transactions for the current month
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transaction/create:
    post:
      security:
        - Bearer: []
      tags:
        - Create a new transaction
      summary: Add a new transaction information for an identified user.
      description: API for adding a new transaction information for an identified user
      operationId: createTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Created transaction object
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Successfully created a transaction!
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transaction/operation/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Read, update and delete an existent transaction
      summary: View the details of a specific transaction in another view.
      description: API for fetching an existent transaction in detail
      operationId: readUniqueTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction unique id
      responses:
        "200":
          description: Successfully get an user's specific transaction!
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Read, update and delete an existent transaction
      summary: Edit a specific transaction information for un identified user.
      description: API for updating an existent transaction
      operationId: updateTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction unique id
        - in: body
          name: body
          description: Updated transaction object
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Successfully updated an user's specific transaction!
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Read, update and delete an existent transaction
      summary: Deletes a specific transaction information for un identified user.
      description: API for deleting an existent transaction
      operationId: deleteTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction unique id
      responses:
        "200":
          description: Successfully delete an existent transaction!
          schema:
            $ref: "#/definitions/TransactionDelete"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          format: int64
          description: User id
          example: 20
        date:
          type: string
          format: date-time
          example: 2022-02-16T09:12:32.766Z
        description:
          type: string
          example: Argent Bank notification
        amount:
          type: integer
          example: 200
        balance:
          type: integer
          example: 5000
        category:
          type: string
          example: monthly billing
        notes:
          type: string
          example: Phone bill for March 2023
    uniqueItems: true
  TransactionDelete:
    type: object
    properties:
      transaction:
        type: object
        properties:
          id:
            type: string
            format: int64
            description: User id
            example: 20
          date:
            type: string
            format: date-time
            example: 2022-02-16T09:12:32.766Z
          description:
            type: string
            example:
          amount:
            type: integer
            example: 200
          balance:
            type: integer
            example: 5000
          category:
            type: string
            example:
          notes:
            type: string
            example:
  Transaction:
    type: object
    properties:
      transaction:
        type: object
        properties:
          id:
            type: string
            format: int64
            description: User id
            example: 20
          date:
            type: string
            format: date-time
            example: 2022-02-16T09:12:32.766Z
          description:
            type: string
            example: Argent Bank notification
          amount:
            type: integer
            example: 200
          balance:
            type: integer
            example: 5000
          category:
            type: string
            example: monthly billing
          notes:
            type: string
            example: Phone bill for March 2023
